given_name = input("Given name: ")
family_name = input("Family name: ")
street_address = input("Street address: ")
city_and_postal_code = input("City and postal code: ")
print(f"{given_name} {family_name}")
print(f"{street_address}")
print(f"{city_and_postal_code}")